// Code generated by protoc-gen-go.
// source: econ_gcmessages.proto
// DO NOT EDIT!

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type EGCItemMsg int32

const (
	EGCItemMsg_k_EMsgGCBase                                 EGCItemMsg = 1000
	EGCItemMsg_k_EMsgGCSetItemPosition                      EGCItemMsg = 1001
	EGCItemMsg_k_EMsgGCCraft                                EGCItemMsg = 1002
	EGCItemMsg_k_EMsgGCCraftResponse                        EGCItemMsg = 1003
	EGCItemMsg_k_EMsgGCDelete                               EGCItemMsg = 1004
	EGCItemMsg_k_EMsgGCVerifyCacheSubscription              EGCItemMsg = 1005
	EGCItemMsg_k_EMsgGCNameItem                             EGCItemMsg = 1006
	EGCItemMsg_k_EMsgGCUnlockCrate                          EGCItemMsg = 1007
	EGCItemMsg_k_EMsgGCUnlockCrateResponse                  EGCItemMsg = 1008
	EGCItemMsg_k_EMsgGCPaintItem                            EGCItemMsg = 1009
	EGCItemMsg_k_EMsgGCPaintItemResponse                    EGCItemMsg = 1010
	EGCItemMsg_k_EMsgGCGoldenWrenchBroadcast                EGCItemMsg = 1011
	EGCItemMsg_k_EMsgGCMOTDRequest                          EGCItemMsg = 1012
	EGCItemMsg_k_EMsgGCMOTDRequestResponse                  EGCItemMsg = 1013
	EGCItemMsg_k_EMsgGCAddItemToSocket_DEPRECATED           EGCItemMsg = 1014
	EGCItemMsg_k_EMsgGCAddItemToSocketResponse_DEPRECATED   EGCItemMsg = 1015
	EGCItemMsg_k_EMsgGCAddSocketToBaseItem_DEPRECATED       EGCItemMsg = 1016
	EGCItemMsg_k_EMsgGCAddSocketToItem_DEPRECATED           EGCItemMsg = 1017
	EGCItemMsg_k_EMsgGCAddSocketToItemResponse_DEPRECATED   EGCItemMsg = 1018
	EGCItemMsg_k_EMsgGCNameBaseItem                         EGCItemMsg = 1019
	EGCItemMsg_k_EMsgGCNameBaseItemResponse                 EGCItemMsg = 1020
	EGCItemMsg_k_EMsgGCRemoveSocketItem_DEPRECATED          EGCItemMsg = 1021
	EGCItemMsg_k_EMsgGCRemoveSocketItemResponse_DEPRECATED  EGCItemMsg = 1022
	EGCItemMsg_k_EMsgGCCustomizeItemTexture                 EGCItemMsg = 1023
	EGCItemMsg_k_EMsgGCCustomizeItemTextureResponse         EGCItemMsg = 1024
	EGCItemMsg_k_EMsgGCUseItemRequest                       EGCItemMsg = 1025
	EGCItemMsg_k_EMsgGCUseItemResponse                      EGCItemMsg = 1026
	EGCItemMsg_k_EMsgGCGiftedItems_DEPRECATED               EGCItemMsg = 1027
	EGCItemMsg_k_EMsgGCRemoveItemName                       EGCItemMsg = 1030
	EGCItemMsg_k_EMsgGCRemoveItemPaint                      EGCItemMsg = 1031
	EGCItemMsg_k_EMsgGCGiftWrapItem                         EGCItemMsg = 1032
	EGCItemMsg_k_EMsgGCGiftWrapItemResponse                 EGCItemMsg = 1033
	EGCItemMsg_k_EMsgGCDeliverGift                          EGCItemMsg = 1034
	EGCItemMsg_k_EMsgGCDeliverGiftResponseGiver             EGCItemMsg = 1035
	EGCItemMsg_k_EMsgGCDeliverGiftResponseReceiver          EGCItemMsg = 1036
	EGCItemMsg_k_EMsgGCUnwrapGiftRequest                    EGCItemMsg = 1037
	EGCItemMsg_k_EMsgGCUnwrapGiftResponse                   EGCItemMsg = 1038
	EGCItemMsg_k_EMsgGCSetItemStyle                         EGCItemMsg = 1039
	EGCItemMsg_k_EMsgGCUsedClaimCodeItem                    EGCItemMsg = 1040
	EGCItemMsg_k_EMsgGCSortItems                            EGCItemMsg = 1041
	EGCItemMsg_k_EMsgGC_RevolvingLootList_DEPRECATED        EGCItemMsg = 1042
	EGCItemMsg_k_EMsgGCLookupAccount                        EGCItemMsg = 1043
	EGCItemMsg_k_EMsgGCLookupAccountResponse                EGCItemMsg = 1044
	EGCItemMsg_k_EMsgGCLookupAccountName                    EGCItemMsg = 1045
	EGCItemMsg_k_EMsgGCLookupAccountNameResponse            EGCItemMsg = 1046
	EGCItemMsg_k_EMsgGCUpdateItemSchema                     EGCItemMsg = 1049
	EGCItemMsg_k_EMsgGCRemoveCustomTexture                  EGCItemMsg = 1051
	EGCItemMsg_k_EMsgGCRemoveCustomTextureResponse          EGCItemMsg = 1052
	EGCItemMsg_k_EMsgGCRemoveMakersMark                     EGCItemMsg = 1053
	EGCItemMsg_k_EMsgGCRemoveMakersMarkResponse             EGCItemMsg = 1054
	EGCItemMsg_k_EMsgGCRemoveUniqueCraftIndex               EGCItemMsg = 1055
	EGCItemMsg_k_EMsgGCRemoveUniqueCraftIndexResponse       EGCItemMsg = 1056
	EGCItemMsg_k_EMsgGCSaxxyBroadcast                       EGCItemMsg = 1057
	EGCItemMsg_k_EMsgGCBackpackSortFinished                 EGCItemMsg = 1058
	EGCItemMsg_k_EMsgGCAdjustItemEquippedState              EGCItemMsg = 1059
	EGCItemMsg_k_EMsgGCCollectItem                          EGCItemMsg = 1061
	EGCItemMsg_k_EMsgGCItemAcknowledged__DEPRECATED         EGCItemMsg = 1062
	EGCItemMsg_k_EMsgGCPresets_SelectPresetForClass         EGCItemMsg = 1063
	EGCItemMsg_k_EMsgGCPresets_SetItemPosition              EGCItemMsg = 1064
	EGCItemMsg_k_EMsgGC_ReportAbuse                         EGCItemMsg = 1065
	EGCItemMsg_k_EMsgGC_ReportAbuseResponse                 EGCItemMsg = 1066
	EGCItemMsg_k_EMsgGCPresets_SelectPresetForClassReply    EGCItemMsg = 1067
	EGCItemMsg_k_EMsgGCNameItemNotification                 EGCItemMsg = 1068
	EGCItemMsg_k_EMsgGCApplyConsumableEffects               EGCItemMsg = 1069
	EGCItemMsg_k_EMsgGCConsumableExhausted                  EGCItemMsg = 1070
	EGCItemMsg_k_EMsgGCShowItemsPickedUp                    EGCItemMsg = 1071
	EGCItemMsg_k_EMsgGCClientDisplayNotification            EGCItemMsg = 1072
	EGCItemMsg_k_EMsgGCApplyStrangePart                     EGCItemMsg = 1073
	EGCItemMsg_k_EMsgGC_IncrementKillCountAttribute         EGCItemMsg = 1074
	EGCItemMsg_k_EMsgGC_IncrementKillCountResponse          EGCItemMsg = 1075
	EGCItemMsg_k_EMsgGCApplyPennantUpgrade                  EGCItemMsg = 1076
	EGCItemMsg_k_EMsgGCSetItemPositions                     EGCItemMsg = 1077
	EGCItemMsg_k_EMsgGCApplyEggEssence                      EGCItemMsg = 1078
	EGCItemMsg_k_EMsgGCNameEggEssenceResponse               EGCItemMsg = 1079
	EGCItemMsg_k_EMsgGCPaintKitItem                         EGCItemMsg = 1080
	EGCItemMsg_k_EMsgGCPaintKitBaseItem                     EGCItemMsg = 1081
	EGCItemMsg_k_EMsgGCPaintKitItemResponse                 EGCItemMsg = 1082
	EGCItemMsg_k_EMsgGCGiftedItems                          EGCItemMsg = 1083
	EGCItemMsg_k_EMsgGCUnlockItemStyle                      EGCItemMsg = 1084
	EGCItemMsg_k_EMsgGCUnlockItemStyleResponse              EGCItemMsg = 1085
	EGCItemMsg_k_EMsgGCApplySticker                         EGCItemMsg = 1086
	EGCItemMsg_k_EMsgGCItemAcknowledged                     EGCItemMsg = 1087
	EGCItemMsg_k_EMsgGCStatTrakSwap                         EGCItemMsg = 1088
	EGCItemMsg_k_EMsgGCTradingBase                          EGCItemMsg = 1500
	EGCItemMsg_k_EMsgGCTrading_InitiateTradeRequest         EGCItemMsg = 1501
	EGCItemMsg_k_EMsgGCTrading_InitiateTradeResponse        EGCItemMsg = 1502
	EGCItemMsg_k_EMsgGCTrading_StartSession                 EGCItemMsg = 1503
	EGCItemMsg_k_EMsgGCTrading_SetItem                      EGCItemMsg = 1504
	EGCItemMsg_k_EMsgGCTrading_RemoveItem                   EGCItemMsg = 1505
	EGCItemMsg_k_EMsgGCTrading_UpdateTradeInfo              EGCItemMsg = 1506
	EGCItemMsg_k_EMsgGCTrading_SetReadiness                 EGCItemMsg = 1507
	EGCItemMsg_k_EMsgGCTrading_ReadinessResponse            EGCItemMsg = 1508
	EGCItemMsg_k_EMsgGCTrading_SessionClosed                EGCItemMsg = 1509
	EGCItemMsg_k_EMsgGCTrading_CancelSession                EGCItemMsg = 1510
	EGCItemMsg_k_EMsgGCTrading_TradeChatMsg                 EGCItemMsg = 1511
	EGCItemMsg_k_EMsgGCTrading_ConfirmOffer                 EGCItemMsg = 1512
	EGCItemMsg_k_EMsgGCTrading_TradeTypingChatMsg           EGCItemMsg = 1513
	EGCItemMsg_k_EMsgGCServerBrowser_FavoriteServer         EGCItemMsg = 1601
	EGCItemMsg_k_EMsgGCServerBrowser_BlacklistServer        EGCItemMsg = 1602
	EGCItemMsg_k_EMsgGCServerRentalsBase                    EGCItemMsg = 1700
	EGCItemMsg_k_EMsgGCItemPreviewCheckStatus               EGCItemMsg = 1701
	EGCItemMsg_k_EMsgGCItemPreviewStatusResponse            EGCItemMsg = 1702
	EGCItemMsg_k_EMsgGCItemPreviewRequest                   EGCItemMsg = 1703
	EGCItemMsg_k_EMsgGCItemPreviewRequestResponse           EGCItemMsg = 1704
	EGCItemMsg_k_EMsgGCItemPreviewExpire                    EGCItemMsg = 1705
	EGCItemMsg_k_EMsgGCItemPreviewExpireNotification        EGCItemMsg = 1706
	EGCItemMsg_k_EMsgGCItemPreviewItemBoughtNotification    EGCItemMsg = 1707
	EGCItemMsg_k_EMsgGCDev_NewItemRequest                   EGCItemMsg = 2001
	EGCItemMsg_k_EMsgGCDev_NewItemRequestResponse           EGCItemMsg = 2002
	EGCItemMsg_k_EMsgGCDev_PaintKitDropItem                 EGCItemMsg = 2003
	EGCItemMsg_k_EMsgGCStoreGetUserData                     EGCItemMsg = 2500
	EGCItemMsg_k_EMsgGCStoreGetUserDataResponse             EGCItemMsg = 2501
	EGCItemMsg_k_EMsgGCStorePurchaseInit_DEPRECATED         EGCItemMsg = 2502
	EGCItemMsg_k_EMsgGCStorePurchaseInitResponse_DEPRECATED EGCItemMsg = 2503
	EGCItemMsg_k_EMsgGCStorePurchaseFinalize                EGCItemMsg = 2504
	EGCItemMsg_k_EMsgGCStorePurchaseFinalizeResponse        EGCItemMsg = 2505
	EGCItemMsg_k_EMsgGCStorePurchaseCancel                  EGCItemMsg = 2506
	EGCItemMsg_k_EMsgGCStorePurchaseCancelResponse          EGCItemMsg = 2507
	EGCItemMsg_k_EMsgGCStorePurchaseQueryTxn                EGCItemMsg = 2508
	EGCItemMsg_k_EMsgGCStorePurchaseQueryTxnResponse        EGCItemMsg = 2509
	EGCItemMsg_k_EMsgGCStorePurchaseInit                    EGCItemMsg = 2510
	EGCItemMsg_k_EMsgGCStorePurchaseInitResponse            EGCItemMsg = 2511
	EGCItemMsg_k_EMsgGCBannedWordListRequest                EGCItemMsg = 2512
	EGCItemMsg_k_EMsgGCBannedWordListResponse               EGCItemMsg = 2513
	EGCItemMsg_k_EMsgGCToGCBannedWordListBroadcast          EGCItemMsg = 2514
	EGCItemMsg_k_EMsgGCToGCBannedWordListUpdated            EGCItemMsg = 2515
	EGCItemMsg_k_EMsgGCToGCDirtySDOCache                    EGCItemMsg = 2516
	EGCItemMsg_k_EMsgGCToGCDirtyMultipleSDOCache            EGCItemMsg = 2517
	EGCItemMsg_k_EMsgGCToGCUpdateSQLKeyValue                EGCItemMsg = 2518
	EGCItemMsg_k_EMsgGCToGCIsTrustedServer                  EGCItemMsg = 2519
	EGCItemMsg_k_EMsgGCToGCIsTrustedServerResponse          EGCItemMsg = 2520
	EGCItemMsg_k_EMsgGCToGCBroadcastConsoleCommand          EGCItemMsg = 2521
	EGCItemMsg_k_EMsgGCServerVersionUpdated                 EGCItemMsg = 2522
	EGCItemMsg_k_EMsgGCApplyAutograph                       EGCItemMsg = 2523
	EGCItemMsg_k_EMsgGCToGCWebAPIAccountChanged             EGCItemMsg = 2524
	EGCItemMsg_k_EMsgGCRequestAnnouncements                 EGCItemMsg = 2525
	EGCItemMsg_k_EMsgGCRequestAnnouncementsResponse         EGCItemMsg = 2526
	EGCItemMsg_k_EMsgGCRequestPassportItemGrant             EGCItemMsg = 2527
	EGCItemMsg_k_EMsgGCClientVersionUpdated                 EGCItemMsg = 2528
)

var EGCItemMsg_name = map[int32]string{
	1000: "k_EMsgGCBase",
	1001: "k_EMsgGCSetItemPosition",
	1002: "k_EMsgGCCraft",
	1003: "k_EMsgGCCraftResponse",
	1004: "k_EMsgGCDelete",
	1005: "k_EMsgGCVerifyCacheSubscription",
	1006: "k_EMsgGCNameItem",
	1007: "k_EMsgGCUnlockCrate",
	1008: "k_EMsgGCUnlockCrateResponse",
	1009: "k_EMsgGCPaintItem",
	1010: "k_EMsgGCPaintItemResponse",
	1011: "k_EMsgGCGoldenWrenchBroadcast",
	1012: "k_EMsgGCMOTDRequest",
	1013: "k_EMsgGCMOTDRequestResponse",
	1014: "k_EMsgGCAddItemToSocket_DEPRECATED",
	1015: "k_EMsgGCAddItemToSocketResponse_DEPRECATED",
	1016: "k_EMsgGCAddSocketToBaseItem_DEPRECATED",
	1017: "k_EMsgGCAddSocketToItem_DEPRECATED",
	1018: "k_EMsgGCAddSocketToItemResponse_DEPRECATED",
	1019: "k_EMsgGCNameBaseItem",
	1020: "k_EMsgGCNameBaseItemResponse",
	1021: "k_EMsgGCRemoveSocketItem_DEPRECATED",
	1022: "k_EMsgGCRemoveSocketItemResponse_DEPRECATED",
	1023: "k_EMsgGCCustomizeItemTexture",
	1024: "k_EMsgGCCustomizeItemTextureResponse",
	1025: "k_EMsgGCUseItemRequest",
	1026: "k_EMsgGCUseItemResponse",
	1027: "k_EMsgGCGiftedItems_DEPRECATED",
	1030: "k_EMsgGCRemoveItemName",
	1031: "k_EMsgGCRemoveItemPaint",
	1032: "k_EMsgGCGiftWrapItem",
	1033: "k_EMsgGCGiftWrapItemResponse",
	1034: "k_EMsgGCDeliverGift",
	1035: "k_EMsgGCDeliverGiftResponseGiver",
	1036: "k_EMsgGCDeliverGiftResponseReceiver",
	1037: "k_EMsgGCUnwrapGiftRequest",
	1038: "k_EMsgGCUnwrapGiftResponse",
	1039: "k_EMsgGCSetItemStyle",
	1040: "k_EMsgGCUsedClaimCodeItem",
	1041: "k_EMsgGCSortItems",
	1042: "k_EMsgGC_RevolvingLootList_DEPRECATED",
	1043: "k_EMsgGCLookupAccount",
	1044: "k_EMsgGCLookupAccountResponse",
	1045: "k_EMsgGCLookupAccountName",
	1046: "k_EMsgGCLookupAccountNameResponse",
	1049: "k_EMsgGCUpdateItemSchema",
	1051: "k_EMsgGCRemoveCustomTexture",
	1052: "k_EMsgGCRemoveCustomTextureResponse",
	1053: "k_EMsgGCRemoveMakersMark",
	1054: "k_EMsgGCRemoveMakersMarkResponse",
	1055: "k_EMsgGCRemoveUniqueCraftIndex",
	1056: "k_EMsgGCRemoveUniqueCraftIndexResponse",
	1057: "k_EMsgGCSaxxyBroadcast",
	1058: "k_EMsgGCBackpackSortFinished",
	1059: "k_EMsgGCAdjustItemEquippedState",
	1061: "k_EMsgGCCollectItem",
	1062: "k_EMsgGCItemAcknowledged__DEPRECATED",
	1063: "k_EMsgGCPresets_SelectPresetForClass",
	1064: "k_EMsgGCPresets_SetItemPosition",
	1065: "k_EMsgGC_ReportAbuse",
	1066: "k_EMsgGC_ReportAbuseResponse",
	1067: "k_EMsgGCPresets_SelectPresetForClassReply",
	1068: "k_EMsgGCNameItemNotification",
	1069: "k_EMsgGCApplyConsumableEffects",
	1070: "k_EMsgGCConsumableExhausted",
	1071: "k_EMsgGCShowItemsPickedUp",
	1072: "k_EMsgGCClientDisplayNotification",
	1073: "k_EMsgGCApplyStrangePart",
	1074: "k_EMsgGC_IncrementKillCountAttribute",
	1075: "k_EMsgGC_IncrementKillCountResponse",
	1076: "k_EMsgGCApplyPennantUpgrade",
	1077: "k_EMsgGCSetItemPositions",
	1078: "k_EMsgGCApplyEggEssence",
	1079: "k_EMsgGCNameEggEssenceResponse",
	1080: "k_EMsgGCPaintKitItem",
	1081: "k_EMsgGCPaintKitBaseItem",
	1082: "k_EMsgGCPaintKitItemResponse",
	1083: "k_EMsgGCGiftedItems",
	1084: "k_EMsgGCUnlockItemStyle",
	1085: "k_EMsgGCUnlockItemStyleResponse",
	1086: "k_EMsgGCApplySticker",
	1087: "k_EMsgGCItemAcknowledged",
	1088: "k_EMsgGCStatTrakSwap",
	1500: "k_EMsgGCTradingBase",
	1501: "k_EMsgGCTrading_InitiateTradeRequest",
	1502: "k_EMsgGCTrading_InitiateTradeResponse",
	1503: "k_EMsgGCTrading_StartSession",
	1504: "k_EMsgGCTrading_SetItem",
	1505: "k_EMsgGCTrading_RemoveItem",
	1506: "k_EMsgGCTrading_UpdateTradeInfo",
	1507: "k_EMsgGCTrading_SetReadiness",
	1508: "k_EMsgGCTrading_ReadinessResponse",
	1509: "k_EMsgGCTrading_SessionClosed",
	1510: "k_EMsgGCTrading_CancelSession",
	1511: "k_EMsgGCTrading_TradeChatMsg",
	1512: "k_EMsgGCTrading_ConfirmOffer",
	1513: "k_EMsgGCTrading_TradeTypingChatMsg",
	1601: "k_EMsgGCServerBrowser_FavoriteServer",
	1602: "k_EMsgGCServerBrowser_BlacklistServer",
	1700: "k_EMsgGCServerRentalsBase",
	1701: "k_EMsgGCItemPreviewCheckStatus",
	1702: "k_EMsgGCItemPreviewStatusResponse",
	1703: "k_EMsgGCItemPreviewRequest",
	1704: "k_EMsgGCItemPreviewRequestResponse",
	1705: "k_EMsgGCItemPreviewExpire",
	1706: "k_EMsgGCItemPreviewExpireNotification",
	1707: "k_EMsgGCItemPreviewItemBoughtNotification",
	2001: "k_EMsgGCDev_NewItemRequest",
	2002: "k_EMsgGCDev_NewItemRequestResponse",
	2003: "k_EMsgGCDev_PaintKitDropItem",
	2500: "k_EMsgGCStoreGetUserData",
	2501: "k_EMsgGCStoreGetUserDataResponse",
	2502: "k_EMsgGCStorePurchaseInit_DEPRECATED",
	2503: "k_EMsgGCStorePurchaseInitResponse_DEPRECATED",
	2504: "k_EMsgGCStorePurchaseFinalize",
	2505: "k_EMsgGCStorePurchaseFinalizeResponse",
	2506: "k_EMsgGCStorePurchaseCancel",
	2507: "k_EMsgGCStorePurchaseCancelResponse",
	2508: "k_EMsgGCStorePurchaseQueryTxn",
	2509: "k_EMsgGCStorePurchaseQueryTxnResponse",
	2510: "k_EMsgGCStorePurchaseInit",
	2511: "k_EMsgGCStorePurchaseInitResponse",
	2512: "k_EMsgGCBannedWordListRequest",
	2513: "k_EMsgGCBannedWordListResponse",
	2514: "k_EMsgGCToGCBannedWordListBroadcast",
	2515: "k_EMsgGCToGCBannedWordListUpdated",
	2516: "k_EMsgGCToGCDirtySDOCache",
	2517: "k_EMsgGCToGCDirtyMultipleSDOCache",
	2518: "k_EMsgGCToGCUpdateSQLKeyValue",
	2519: "k_EMsgGCToGCIsTrustedServer",
	2520: "k_EMsgGCToGCIsTrustedServerResponse",
	2521: "k_EMsgGCToGCBroadcastConsoleCommand",
	2522: "k_EMsgGCServerVersionUpdated",
	2523: "k_EMsgGCApplyAutograph",
	2524: "k_EMsgGCToGCWebAPIAccountChanged",
	2525: "k_EMsgGCRequestAnnouncements",
	2526: "k_EMsgGCRequestAnnouncementsResponse",
	2527: "k_EMsgGCRequestPassportItemGrant",
	2528: "k_EMsgGCClientVersionUpdated",
}
var EGCItemMsg_value = map[string]int32{
	"k_EMsgGCBase":                                 1000,
	"k_EMsgGCSetItemPosition":                      1001,
	"k_EMsgGCCraft":                                1002,
	"k_EMsgGCCraftResponse":                        1003,
	"k_EMsgGCDelete":                               1004,
	"k_EMsgGCVerifyCacheSubscription":              1005,
	"k_EMsgGCNameItem":                             1006,
	"k_EMsgGCUnlockCrate":                          1007,
	"k_EMsgGCUnlockCrateResponse":                  1008,
	"k_EMsgGCPaintItem":                            1009,
	"k_EMsgGCPaintItemResponse":                    1010,
	"k_EMsgGCGoldenWrenchBroadcast":                1011,
	"k_EMsgGCMOTDRequest":                          1012,
	"k_EMsgGCMOTDRequestResponse":                  1013,
	"k_EMsgGCAddItemToSocket_DEPRECATED":           1014,
	"k_EMsgGCAddItemToSocketResponse_DEPRECATED":   1015,
	"k_EMsgGCAddSocketToBaseItem_DEPRECATED":       1016,
	"k_EMsgGCAddSocketToItem_DEPRECATED":           1017,
	"k_EMsgGCAddSocketToItemResponse_DEPRECATED":   1018,
	"k_EMsgGCNameBaseItem":                         1019,
	"k_EMsgGCNameBaseItemResponse":                 1020,
	"k_EMsgGCRemoveSocketItem_DEPRECATED":          1021,
	"k_EMsgGCRemoveSocketItemResponse_DEPRECATED":  1022,
	"k_EMsgGCCustomizeItemTexture":                 1023,
	"k_EMsgGCCustomizeItemTextureResponse":         1024,
	"k_EMsgGCUseItemRequest":                       1025,
	"k_EMsgGCUseItemResponse":                      1026,
	"k_EMsgGCGiftedItems_DEPRECATED":               1027,
	"k_EMsgGCRemoveItemName":                       1030,
	"k_EMsgGCRemoveItemPaint":                      1031,
	"k_EMsgGCGiftWrapItem":                         1032,
	"k_EMsgGCGiftWrapItemResponse":                 1033,
	"k_EMsgGCDeliverGift":                          1034,
	"k_EMsgGCDeliverGiftResponseGiver":             1035,
	"k_EMsgGCDeliverGiftResponseReceiver":          1036,
	"k_EMsgGCUnwrapGiftRequest":                    1037,
	"k_EMsgGCUnwrapGiftResponse":                   1038,
	"k_EMsgGCSetItemStyle":                         1039,
	"k_EMsgGCUsedClaimCodeItem":                    1040,
	"k_EMsgGCSortItems":                            1041,
	"k_EMsgGC_RevolvingLootList_DEPRECATED":        1042,
	"k_EMsgGCLookupAccount":                        1043,
	"k_EMsgGCLookupAccountResponse":                1044,
	"k_EMsgGCLookupAccountName":                    1045,
	"k_EMsgGCLookupAccountNameResponse":            1046,
	"k_EMsgGCUpdateItemSchema":                     1049,
	"k_EMsgGCRemoveCustomTexture":                  1051,
	"k_EMsgGCRemoveCustomTextureResponse":          1052,
	"k_EMsgGCRemoveMakersMark":                     1053,
	"k_EMsgGCRemoveMakersMarkResponse":             1054,
	"k_EMsgGCRemoveUniqueCraftIndex":               1055,
	"k_EMsgGCRemoveUniqueCraftIndexResponse":       1056,
	"k_EMsgGCSaxxyBroadcast":                       1057,
	"k_EMsgGCBackpackSortFinished":                 1058,
	"k_EMsgGCAdjustItemEquippedState":              1059,
	"k_EMsgGCCollectItem":                          1061,
	"k_EMsgGCItemAcknowledged__DEPRECATED":         1062,
	"k_EMsgGCPresets_SelectPresetForClass":         1063,
	"k_EMsgGCPresets_SetItemPosition":              1064,
	"k_EMsgGC_ReportAbuse":                         1065,
	"k_EMsgGC_ReportAbuseResponse":                 1066,
	"k_EMsgGCPresets_SelectPresetForClassReply":    1067,
	"k_EMsgGCNameItemNotification":                 1068,
	"k_EMsgGCApplyConsumableEffects":               1069,
	"k_EMsgGCConsumableExhausted":                  1070,
	"k_EMsgGCShowItemsPickedUp":                    1071,
	"k_EMsgGCClientDisplayNotification":            1072,
	"k_EMsgGCApplyStrangePart":                     1073,
	"k_EMsgGC_IncrementKillCountAttribute":         1074,
	"k_EMsgGC_IncrementKillCountResponse":          1075,
	"k_EMsgGCApplyPennantUpgrade":                  1076,
	"k_EMsgGCSetItemPositions":                     1077,
	"k_EMsgGCApplyEggEssence":                      1078,
	"k_EMsgGCNameEggEssenceResponse":               1079,
	"k_EMsgGCPaintKitItem":                         1080,
	"k_EMsgGCPaintKitBaseItem":                     1081,
	"k_EMsgGCPaintKitItemResponse":                 1082,
	"k_EMsgGCGiftedItems":                          1083,
	"k_EMsgGCUnlockItemStyle":                      1084,
	"k_EMsgGCUnlockItemStyleResponse":              1085,
	"k_EMsgGCApplySticker":                         1086,
	"k_EMsgGCItemAcknowledged":                     1087,
	"k_EMsgGCStatTrakSwap":                         1088,
	"k_EMsgGCTradingBase":                          1500,
	"k_EMsgGCTrading_InitiateTradeRequest":         1501,
	"k_EMsgGCTrading_InitiateTradeResponse":        1502,
	"k_EMsgGCTrading_StartSession":                 1503,
	"k_EMsgGCTrading_SetItem":                      1504,
	"k_EMsgGCTrading_RemoveItem":                   1505,
	"k_EMsgGCTrading_UpdateTradeInfo":              1506,
	"k_EMsgGCTrading_SetReadiness":                 1507,
	"k_EMsgGCTrading_ReadinessResponse":            1508,
	"k_EMsgGCTrading_SessionClosed":                1509,
	"k_EMsgGCTrading_CancelSession":                1510,
	"k_EMsgGCTrading_TradeChatMsg":                 1511,
	"k_EMsgGCTrading_ConfirmOffer":                 1512,
	"k_EMsgGCTrading_TradeTypingChatMsg":           1513,
	"k_EMsgGCServerBrowser_FavoriteServer":         1601,
	"k_EMsgGCServerBrowser_BlacklistServer":        1602,
	"k_EMsgGCServerRentalsBase":                    1700,
	"k_EMsgGCItemPreviewCheckStatus":               1701,
	"k_EMsgGCItemPreviewStatusResponse":            1702,
	"k_EMsgGCItemPreviewRequest":                   1703,
	"k_EMsgGCItemPreviewRequestResponse":           1704,
	"k_EMsgGCItemPreviewExpire":                    1705,
	"k_EMsgGCItemPreviewExpireNotification":        1706,
	"k_EMsgGCItemPreviewItemBoughtNotification":    1707,
	"k_EMsgGCDev_NewItemRequest":                   2001,
	"k_EMsgGCDev_NewItemRequestResponse":           2002,
	"k_EMsgGCDev_PaintKitDropItem":                 2003,
	"k_EMsgGCStoreGetUserData":                     2500,
	"k_EMsgGCStoreGetUserDataResponse":             2501,
	"k_EMsgGCStorePurchaseInit_DEPRECATED":         2502,
	"k_EMsgGCStorePurchaseInitResponse_DEPRECATED": 2503,
	"k_EMsgGCStorePurchaseFinalize":                2504,
	"k_EMsgGCStorePurchaseFinalizeResponse":        2505,
	"k_EMsgGCStorePurchaseCancel":                  2506,
	"k_EMsgGCStorePurchaseCancelResponse":          2507,
	"k_EMsgGCStorePurchaseQueryTxn":                2508,
	"k_EMsgGCStorePurchaseQueryTxnResponse":        2509,
	"k_EMsgGCStorePurchaseInit":                    2510,
	"k_EMsgGCStorePurchaseInitResponse":            2511,
	"k_EMsgGCBannedWordListRequest":                2512,
	"k_EMsgGCBannedWordListResponse":               2513,
	"k_EMsgGCToGCBannedWordListBroadcast":          2514,
	"k_EMsgGCToGCBannedWordListUpdated":            2515,
	"k_EMsgGCToGCDirtySDOCache":                    2516,
	"k_EMsgGCToGCDirtyMultipleSDOCache":            2517,
	"k_EMsgGCToGCUpdateSQLKeyValue":                2518,
	"k_EMsgGCToGCIsTrustedServer":                  2519,
	"k_EMsgGCToGCIsTrustedServerResponse":          2520,
	"k_EMsgGCToGCBroadcastConsoleCommand":          2521,
	"k_EMsgGCServerVersionUpdated":                 2522,
	"k_EMsgGCApplyAutograph":                       2523,
	"k_EMsgGCToGCWebAPIAccountChanged":             2524,
	"k_EMsgGCRequestAnnouncements":                 2525,
	"k_EMsgGCRequestAnnouncementsResponse":         2526,
	"k_EMsgGCRequestPassportItemGrant":             2527,
	"k_EMsgGCClientVersionUpdated":                 2528,
}

func (x EGCItemMsg) Enum() *EGCItemMsg {
	p := new(EGCItemMsg)
	*p = x
	return p
}
func (x EGCItemMsg) String() string {
	return proto.EnumName(EGCItemMsg_name, int32(x))
}
func (x *EGCItemMsg) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EGCItemMsg_value, data, "EGCItemMsg")
	if err != nil {
		return err
	}
	*x = EGCItemMsg(value)
	return nil
}
func (EGCItemMsg) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

type EGCMsgResponse int32

const (
	EGCMsgResponse_k_EGCMsgResponseOK           EGCMsgResponse = 0
	EGCMsgResponse_k_EGCMsgResponseDenied       EGCMsgResponse = 1
	EGCMsgResponse_k_EGCMsgResponseServerError  EGCMsgResponse = 2
	EGCMsgResponse_k_EGCMsgResponseTimeout      EGCMsgResponse = 3
	EGCMsgResponse_k_EGCMsgResponseInvalid      EGCMsgResponse = 4
	EGCMsgResponse_k_EGCMsgResponseNoMatch      EGCMsgResponse = 5
	EGCMsgResponse_k_EGCMsgResponseUnknownError EGCMsgResponse = 6
	EGCMsgResponse_k_EGCMsgResponseNotLoggedOn  EGCMsgResponse = 7
	EGCMsgResponse_k_EGCMsgFailedToCreate       EGCMsgResponse = 8
)

var EGCMsgResponse_name = map[int32]string{
	0: "k_EGCMsgResponseOK",
	1: "k_EGCMsgResponseDenied",
	2: "k_EGCMsgResponseServerError",
	3: "k_EGCMsgResponseTimeout",
	4: "k_EGCMsgResponseInvalid",
	5: "k_EGCMsgResponseNoMatch",
	6: "k_EGCMsgResponseUnknownError",
	7: "k_EGCMsgResponseNotLoggedOn",
	8: "k_EGCMsgFailedToCreate",
}
var EGCMsgResponse_value = map[string]int32{
	"k_EGCMsgResponseOK":           0,
	"k_EGCMsgResponseDenied":       1,
	"k_EGCMsgResponseServerError":  2,
	"k_EGCMsgResponseTimeout":      3,
	"k_EGCMsgResponseInvalid":      4,
	"k_EGCMsgResponseNoMatch":      5,
	"k_EGCMsgResponseUnknownError": 6,
	"k_EGCMsgResponseNotLoggedOn":  7,
	"k_EGCMsgFailedToCreate":       8,
}

func (x EGCMsgResponse) Enum() *EGCMsgResponse {
	p := new(EGCMsgResponse)
	*p = x
	return p
}
func (x EGCMsgResponse) String() string {
	return proto.EnumName(EGCMsgResponse_name, int32(x))
}
func (x *EGCMsgResponse) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EGCMsgResponse_value, data, "EGCMsgResponse")
	if err != nil {
		return err
	}
	*x = EGCMsgResponse(value)
	return nil
}
func (EGCMsgResponse) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

type EUnlockStyle int32

const (
	EUnlockStyle_k_UnlockStyle_Succeeded               EUnlockStyle = 0
	EUnlockStyle_k_UnlockStyle_Failed_PreReq           EUnlockStyle = 1
	EUnlockStyle_k_UnlockStyle_Failed_CantAfford       EUnlockStyle = 2
	EUnlockStyle_k_UnlockStyle_Failed_CantCommit       EUnlockStyle = 3
	EUnlockStyle_k_UnlockStyle_Failed_CantLockCache    EUnlockStyle = 4
	EUnlockStyle_k_UnlockStyle_Failed_CantAffordAttrib EUnlockStyle = 5
)

var EUnlockStyle_name = map[int32]string{
	0: "k_UnlockStyle_Succeeded",
	1: "k_UnlockStyle_Failed_PreReq",
	2: "k_UnlockStyle_Failed_CantAfford",
	3: "k_UnlockStyle_Failed_CantCommit",
	4: "k_UnlockStyle_Failed_CantLockCache",
	5: "k_UnlockStyle_Failed_CantAffordAttrib",
}
var EUnlockStyle_value = map[string]int32{
	"k_UnlockStyle_Succeeded":               0,
	"k_UnlockStyle_Failed_PreReq":           1,
	"k_UnlockStyle_Failed_CantAfford":       2,
	"k_UnlockStyle_Failed_CantCommit":       3,
	"k_UnlockStyle_Failed_CantLockCache":    4,
	"k_UnlockStyle_Failed_CantAffordAttrib": 5,
}

func (x EUnlockStyle) Enum() *EUnlockStyle {
	p := new(EUnlockStyle)
	*p = x
	return p
}
func (x EUnlockStyle) String() string {
	return proto.EnumName(EUnlockStyle_name, int32(x))
}
func (x *EUnlockStyle) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EUnlockStyle_value, data, "EUnlockStyle")
	if err != nil {
		return err
	}
	*x = EUnlockStyle(value)
	return nil
}
func (EUnlockStyle) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

type CMsgGCGiftedItems struct {
	Accountid             *uint32  `protobuf:"varint,1,opt,name=accountid" json:"accountid,omitempty"`
	Giftdefindex          *uint32  `protobuf:"varint,2,opt,name=giftdefindex" json:"giftdefindex,omitempty"`
	MaxGiftsPossible      *uint32  `protobuf:"varint,3,opt,name=max_gifts_possible" json:"max_gifts_possible,omitempty"`
	NumEligibleRecipients *uint32  `protobuf:"varint,4,opt,name=num_eligible_recipients" json:"num_eligible_recipients,omitempty"`
	RecipientsAccountids  []uint32 `protobuf:"varint,5,rep,name=recipients_accountids" json:"recipients_accountids,omitempty"`
	XXX_unrecognized      []byte   `json:"-"`
}

func (m *CMsgGCGiftedItems) Reset()                    { *m = CMsgGCGiftedItems{} }
func (m *CMsgGCGiftedItems) String() string            { return proto.CompactTextString(m) }
func (*CMsgGCGiftedItems) ProtoMessage()               {}
func (*CMsgGCGiftedItems) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *CMsgGCGiftedItems) GetAccountid() uint32 {
	if m != nil && m.Accountid != nil {
		return *m.Accountid
	}
	return 0
}

func (m *CMsgGCGiftedItems) GetGiftdefindex() uint32 {
	if m != nil && m.Giftdefindex != nil {
		return *m.Giftdefindex
	}
	return 0
}

func (m *CMsgGCGiftedItems) GetMaxGiftsPossible() uint32 {
	if m != nil && m.MaxGiftsPossible != nil {
		return *m.MaxGiftsPossible
	}
	return 0
}

func (m *CMsgGCGiftedItems) GetNumEligibleRecipients() uint32 {
	if m != nil && m.NumEligibleRecipients != nil {
		return *m.NumEligibleRecipients
	}
	return 0
}

func (m *CMsgGCGiftedItems) GetRecipientsAccountids() []uint32 {
	if m != nil {
		return m.RecipientsAccountids
	}
	return nil
}

type CMsgApplyAutograph struct {
	AutographItemId  *uint64 `protobuf:"varint,1,opt,name=autograph_item_id" json:"autograph_item_id,omitempty"`
	ItemItemId       *uint64 `protobuf:"varint,2,opt,name=item_item_id" json:"item_item_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgApplyAutograph) Reset()                    { *m = CMsgApplyAutograph{} }
func (m *CMsgApplyAutograph) String() string            { return proto.CompactTextString(m) }
func (*CMsgApplyAutograph) ProtoMessage()               {}
func (*CMsgApplyAutograph) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *CMsgApplyAutograph) GetAutographItemId() uint64 {
	if m != nil && m.AutographItemId != nil {
		return *m.AutographItemId
	}
	return 0
}

func (m *CMsgApplyAutograph) GetItemItemId() uint64 {
	if m != nil && m.ItemItemId != nil {
		return *m.ItemItemId
	}
	return 0
}

func init() {
	proto.RegisterType((*CMsgGCGiftedItems)(nil), "CMsgGCGiftedItems")
	proto.RegisterType((*CMsgApplyAutograph)(nil), "CMsgApplyAutograph")
	proto.RegisterEnum("EGCItemMsg", EGCItemMsg_name, EGCItemMsg_value)
	proto.RegisterEnum("EGCMsgResponse", EGCMsgResponse_name, EGCMsgResponse_value)
	proto.RegisterEnum("EUnlockStyle", EUnlockStyle_name, EUnlockStyle_value)
}

var fileDescriptor3 = []byte{
	// 2192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x58, 0xe7, 0x73, 0xdc, 0xc6,
	0x15, 0x17, 0x25, 0x2a, 0x40, 0x40, 0x9e, 0xb5, 0xc2, 0x59, 0x12, 0x2d, 0xc9, 0xb6, 0x2c, 0x59,
	0x8a, 0x4c, 0x67, 0x9c, 0xe4, 0x4f, 0x38, 0xe2, 0x4e, 0x0c, 0x47, 0xa4, 0x78, 0xe6, 0x1d, 0xa5,
	0x99, 0x7c, 0xb9, 0x59, 0x02, 0x7b, 0x77, 0x1b, 0xe2, 0xb0, 0xd0, 0x02, 0x20, 0x79, 0xf9, 0xe4,
	0x24, 0x33, 0xe9, 0xbd, 0x4d, 0x32, 0x4e, 0x4f, 0xdc, 0xd3, 0x7b, 0x6f, 0x93, 0xde, 0x6d, 0xc7,
	0xa9, 0x76, 0xec, 0x74, 0x2b, 0xbd, 0xf7, 0xf6, 0x76, 0x71, 0xc0, 0xed, 0x82, 0xa0, 0x93, 0x0f,
	0x9a, 0x11, 0xf7, 0xfd, 0xf0, 0xf6, 0xf7, 0xfa, 0xdb, 0xb3, 0x0e, 0x10, 0x97, 0x05, 0x9d, 0x9e,
	0x3b, 0x20, 0x51, 0x84, 0x7b, 0x24, 0xba, 0x21, 0xe4, 0x2c, 0x66, 0x87, 0xab, 0x51, 0x4c, 0xf0,
	0x40, 0x3f, 0x3c, 0xfe, 0xca, 0x09, 0x6b, 0xbf, 0xb3, 0x14, 0xf5, 0xe6, 0x9d, 0x79, 0xda, 0x8d,
	0x89, 0xb7, 0x10, 0x93, 0x41, 0x64, 0xef, 0xb7, 0x1e, 0x8d, 0x5d, 0x97, 0x25, 0x41, 0x4c, 0xbd,
	0x99, 0x89, 0x63, 0x13, 0xa7, 0x2b, 0xf6, 0xe5, 0xd6, 0x74, 0x0f, 0x10, 0x1e, 0xe9, 0xd2, 0xc0,
	0x23, 0x5b, 0x33, 0xbb, 0xe5, 0xe9, 0x61, 0xcb, 0x1e, 0xe0, 0xad, 0x8e, 0x90, 0x44, 0x9d, 0x90,
	0x45, 0x11, 0x5d, 0xf3, 0xc9, 0xcc, 0x1e, 0x29, 0xbb, 0xda, 0x3a, 0x14, 0x24, 0x83, 0x0e, 0xf1,
	0x69, 0x4f, 0x9c, 0x76, 0x38, 0x71, 0x69, 0x48, 0x49, 0x10, 0x47, 0x33, 0x93, 0x12, 0x70, 0xa5,
	0x75, 0x60, 0x7c, 0xd6, 0xc9, 0x2f, 0x8c, 0x66, 0xf6, 0x1e, 0xdb, 0x73, 0xba, 0x72, 0xbc, 0x61,
	0xd9, 0x82, 0x59, 0x2d, 0x0c, 0xfd, 0x61, 0x2d, 0x89, 0x59, 0x8f, 0xe3, 0xb0, 0x6f, 0x5f, 0x61,
	0xed, 0xc7, 0xd9, 0x1f, 0x1d, 0x0a, 0x6c, 0x3b, 0x23, 0x8a, 0x93, 0x82, 0x62, 0x7a, 0x30, 0x3a,
	0x15, 0x14, 0x27, 0x67, 0xef, 0x3b, 0x65, 0x59, 0x8d, 0x79, 0x47, 0x18, 0x06, 0xda, 0xc0, 0xb4,
	0xe9, 0xf5, 0x4e, 0x43, 0x5a, 0x3c, 0x87, 0x23, 0x82, 0x1e, 0x36, 0xec, 0xa3, 0xd6, 0xa1, 0xec,
	0xa8, 0x45, 0x62, 0x01, 0x6c, 0xb2, 0x88, 0xc6, 0x94, 0x05, 0xe8, 0x92, 0x61, 0xdb, 0x56, 0x25,
	0x93, 0x3a, 0x1c, 0x77, 0x63, 0xf4, 0x73, 0x03, 0xcc, 0x3e, 0xa0, 0x9d, 0xad, 0x90, 0x28, 0x64,
	0x01, 0x68, 0xfb, 0x85, 0x61, 0x57, 0xad, 0xcb, 0x32, 0x59, 0x9d, 0xf8, 0x24, 0x26, 0xe8, 0x97,
	0x86, 0x7d, 0xad, 0x75, 0x75, 0x76, 0x78, 0x9e, 0x70, 0xda, 0x1d, 0x3a, 0xd8, 0xed, 0x93, 0x56,
	0xb2, 0x16, 0xb9, 0x9c, 0x86, 0xf2, 0xaa, 0x5f, 0x19, 0xf6, 0x01, 0x0b, 0x65, 0xa8, 0x73, 0x78,
	0x40, 0x04, 0x13, 0xf4, 0x6b, 0xc3, 0x9e, 0xb1, 0xaa, 0xd9, 0xf1, 0x6a, 0xe0, 0x33, 0x77, 0x1d,
	0xee, 0x04, 0xb5, 0xbf, 0x31, 0xec, 0x63, 0xd6, 0x91, 0x12, 0x49, 0xce, 0xe6, 0xb7, 0x86, 0x7d,
	0xd0, 0xda, 0x9f, 0x21, 0x9a, 0x98, 0x06, 0xd2, 0x3a, 0xf4, 0x3b, 0xc3, 0xbe, 0xca, 0xba, 0x62,
	0xdb, 0x79, 0xfe, 0xdd, 0xef, 0x0d, 0xfb, 0xb8, 0x75, 0x65, 0x26, 0x9f, 0x67, 0xbe, 0x47, 0x82,
	0x0b, 0x9c, 0x04, 0x6e, 0x7f, 0x8e, 0x33, 0xec, 0xb9, 0x38, 0x8a, 0xd1, 0x1f, 0x34, 0x5e, 0x4b,
	0xcb, 0xed, 0xfa, 0x0a, 0xb9, 0x98, 0x10, 0x90, 0xfc, 0x51, 0xe3, 0xa5, 0x48, 0x72, 0xfd, 0x7f,
	0x32, 0xec, 0xc7, 0x58, 0xc7, 0x33, 0x44, 0xcd, 0x93, 0x59, 0xd7, 0x66, 0x2d, 0x30, 0x80, 0xc4,
	0x9d, 0x7a, 0xa3, 0xb9, 0xd2, 0x70, 0x6a, 0xed, 0x46, 0x1d, 0xfd, 0xd9, 0xb0, 0x1f, 0x67, 0xcd,
	0xee, 0x00, 0xcc, 0xd4, 0xa9, 0x1f, 0xfc, 0xc5, 0xb0, 0xaf, 0xb7, 0x4e, 0x29, 0x1f, 0xa4, 0xd0,
	0x36, 0x13, 0xb1, 0x16, 0x1f, 0xab, 0xe0, 0xbf, 0x16, 0x69, 0x64, 0xe0, 0x22, 0xf0, 0x6f, 0x45,
	0x1a, 0x2a, 0xb0, 0x8c, 0xc6, 0xdf, 0x0d, 0xc8, 0xd3, 0xcb, 0xd5, 0x58, 0x66, 0xf7, 0xa3, 0x7f,
	0x18, 0xf6, 0x35, 0xd6, 0xd1, 0x32, 0x51, 0xee, 0x9e, 0x7f, 0x1a, 0xf6, 0x69, 0xeb, 0x44, 0x06,
	0x59, 0x21, 0x03, 0xb6, 0x41, 0xd2, 0x1b, 0x8b, 0xc4, 0xfe, 0x65, 0xd8, 0x8f, 0xb7, 0xae, 0xdf,
	0x09, 0x59, 0xc6, 0xec, 0xdf, 0xda, 0xf5, 0x4e, 0x12, 0xc5, 0x6c, 0x40, 0x9f, 0x22, 0xef, 0x6f,
	0x93, 0xad, 0x38, 0xe1, 0x04, 0xfd, 0xc7, 0xb0, 0xaf, 0xb3, 0xae, 0x7d, 0x24, 0x48, 0xce, 0xf4,
	0x26, 0xd3, 0x3e, 0x62, 0x1d, 0xcc, 0x53, 0x30, 0xb3, 0x23, 0xcd, 0x83, 0xa7, 0x9a, 0x6a, 0x65,
	0xad, 0x16, 0x8c, 0x7c, 0x9a, 0x69, 0x9f, 0xb0, 0xae, 0xca, 0x73, 0x6c, 0xdc, 0x7c, 0x54, 0xb6,
	0x4f, 0xd7, 0xf4, 0xa7, 0xf6, 0x09, 0x90, 0x70, 0x1b, 0x7a, 0x86, 0xa6, 0x7f, 0x2c, 0x94, 0xf9,
	0x8c, 0x9e, 0x69, 0xaa, 0x21, 0x10, 0xfa, 0x2f, 0x40, 0xcb, 0x90, 0x21, 0x78, 0x96, 0xa9, 0xfa,
	0x40, 0x15, 0xe5, 0xec, 0x9e, 0x6d, 0xaa, 0xd9, 0x0d, 0x75, 0x4c, 0x37, 0x08, 0x17, 0x48, 0xf4,
	0x1c, 0xd3, 0x3e, 0x69, 0x1d, 0x2b, 0x91, 0x64, 0xdf, 0xce, 0x8b, 0x03, 0xf4, 0x5c, 0x53, 0x8d,
	0x61, 0x09, 0x6c, 0x85, 0xb8, 0x44, 0x22, 0x9f, 0x67, 0xaa, 0xc5, 0xb8, 0x1a, 0x6c, 0x02, 0x97,
	0x14, 0x98, 0xba, 0xf1, 0xf9, 0x26, 0x74, 0xd2, 0xc3, 0x65, 0xf2, 0x11, 0xd7, 0x17, 0x68, 0x96,
	0x8e, 0x3a, 0x58, 0x2b, 0x1e, 0xfa, 0x04, 0xbd, 0x50, 0xd7, 0x1d, 0x11, 0xcf, 0xf1, 0x31, 0x1d,
	0x38, 0xcc, 0x4b, 0x93, 0xf1, 0x45, 0xa6, 0xda, 0x20, 0x5a, 0x8c, 0xcb, 0x6f, 0x23, 0xf4, 0x62,
	0xd3, 0x9e, 0xb5, 0x4e, 0x66, 0xe7, 0x9d, 0x15, 0xb2, 0xc1, 0xfc, 0x0d, 0x1a, 0xf4, 0x16, 0x19,
	0x8b, 0x17, 0x69, 0xa4, 0xd5, 0xe8, 0x4b, 0x4c, 0xb5, 0x1d, 0x02, 0x62, 0x3d, 0x09, 0x6b, 0x69,
	0x2f, 0x47, 0x2f, 0x35, 0xd5, 0x46, 0xa2, 0xc9, 0x72, 0xfa, 0x2f, 0xd3, 0x38, 0x6a, 0x18, 0x19,
	0xe6, 0x97, 0x9b, 0xf6, 0x29, 0xeb, 0x9a, 0x1d, 0xe5, 0xb9, 0x9e, 0x57, 0x98, 0x30, 0x50, 0x66,
	0x72, 0x5b, 0x43, 0x0f, 0x3a, 0xa1, 0xf4, 0x04, 0x34, 0xda, 0x01, 0x46, 0xaf, 0x32, 0xd5, 0xae,
	0x94, 0x66, 0x4b, 0x9a, 0xdb, 0x59, 0xde, 0xdf, 0x6c, 0x6e, 0x2f, 0x3b, 0x0d, 0x91, 0x5f, 0xf5,
	0x6a, 0xed, 0xaa, 0x14, 0xb9, 0x84, 0xd7, 0x09, 0x8f, 0x96, 0x30, 0x5f, 0x47, 0xaf, 0xd1, 0x52,
	0xa4, 0x28, 0xce, 0xb5, 0xbc, 0x56, 0xab, 0x80, 0x14, 0xb6, 0x1a, 0x50, 0x88, 0xba, 0x9c, 0x29,
	0x0b, 0x62, 0xcc, 0xa2, 0xd7, 0x99, 0x6a, 0x43, 0x2b, 0x07, 0xe5, 0x1a, 0x5f, 0xaf, 0x95, 0x4b,
	0x0b, 0x6f, 0x6d, 0x0d, 0xc7, 0x0d, 0xfb, 0x0d, 0x5a, 0xd6, 0xcf, 0x61, 0x77, 0x3d, 0x84, 0x7f,
	0x22, 0xe6, 0x67, 0x68, 0x40, 0xa3, 0x3e, 0xf1, 0xd0, 0x1b, 0x4d, 0x75, 0x50, 0xd5, 0xbc, 0x27,
	0x83, 0xf5, 0xc2, 0x85, 0x8d, 0x8b, 0x09, 0x0d, 0x43, 0xe2, 0xb5, 0x62, 0x31, 0x77, 0xde, 0xa4,
	0xd5, 0x86, 0xc3, 0x7c, 0x9f, 0xb8, 0xe9, 0x5c, 0xb9, 0xc5, 0x54, 0x3b, 0x87, 0x38, 0xaa, 0xb9,
	0xeb, 0x01, 0xdb, 0xf4, 0x89, 0xd7, 0x23, 0x5e, 0x47, 0xcd, 0x9a, 0x5b, 0x35, 0x68, 0x93, 0x93,
	0x88, 0xc0, 0x0e, 0xd0, 0x22, 0x42, 0x57, 0xfa, 0xd7, 0x19, 0xc6, 0x21, 0x59, 0xa3, 0x08, 0xdd,
	0xa6, 0xb1, 0x1a, 0x43, 0xf5, 0x49, 0x7d, 0xbb, 0x56, 0x05, 0x90, 0xb2, 0x21, 0x58, 0x56, 0x5b,
	0x4b, 0xc0, 0x2d, 0x77, 0x68, 0x96, 0xab, 0xa2, 0xdc, 0x73, 0x77, 0x9a, 0xf6, 0x0d, 0xd6, 0x75,
	0xff, 0x0f, 0x1d, 0xf8, 0xda, 0x1f, 0xa2, 0xbb, 0xcc, 0x62, 0x17, 0x97, 0x6d, 0x89, 0xc5, 0xb4,
	0x4b, 0x5d, 0x2c, 0x09, 0xbd, 0x45, 0x0b, 0xaf, 0xdc, 0x62, 0x1c, 0xb8, 0x2b, 0x19, 0x60, 0x58,
	0x86, 0x1a, 0xdd, 0x2e, 0x68, 0x8e, 0xd0, 0x5b, 0xb5, 0xac, 0x54, 0xe4, 0x5b, 0x7d, 0x0c, 0xce,
	0x87, 0x98, 0xbc, 0x4d, 0x2b, 0x8f, 0x56, 0x9f, 0x6d, 0xca, 0x12, 0x6d, 0x52, 0xe8, 0xf2, 0xde,
	0x6a, 0x88, 0xde, 0xae, 0x95, 0x87, 0xe3, 0x8b, 0x65, 0xaa, 0x4e, 0xa3, 0xd0, 0xc7, 0x43, 0x8d,
	0xce, 0x3b, 0xb4, 0x9c, 0x95, 0x74, 0x5a, 0x31, 0xc7, 0x41, 0x8f, 0x34, 0x31, 0x8f, 0xd1, 0x3b,
	0xb5, 0x78, 0x74, 0x16, 0x02, 0x97, 0x93, 0x01, 0xa8, 0x3a, 0x4b, 0x7d, 0xdf, 0x11, 0xb5, 0x56,
	0x8b, 0x63, 0x4e, 0xd7, 0x12, 0x88, 0xff, 0xbb, 0xb4, 0x3a, 0x29, 0x81, 0xe6, 0x5e, 0x7d, 0xb7,
	0x66, 0x9d, 0xbc, 0xb3, 0x49, 0x82, 0x00, 0x07, 0xf1, 0x6a, 0x08, 0x0b, 0x9c, 0x47, 0xd0, 0x7b,
	0x34, 0x56, 0x85, 0x98, 0x46, 0xe8, 0xbd, 0x5a, 0x8b, 0x97, 0x0a, 0x1a, 0xbd, 0x5e, 0x23, 0x8a,
	0x60, 0x17, 0x21, 0xe8, 0x7d, 0x9a, 0x87, 0x45, 0x10, 0xc6, 0xc2, 0x9c, 0xc3, 0xfb, 0xb5, 0xbc,
	0x90, 0xb3, 0xe1, 0x2c, 0x4d, 0xd3, 0xf5, 0x03, 0xda, 0xe5, 0x99, 0x28, 0x9f, 0xd4, 0x1f, 0xd4,
	0x62, 0xac, 0x7e, 0x99, 0x2b, 0xff, 0x90, 0x56, 0x0a, 0xca, 0x10, 0x43, 0x1f, 0xd6, 0x87, 0x9f,
	0x5c, 0xce, 0xc6, 0x7d, 0xf9, 0x23, 0x5a, 0x4a, 0x17, 0xa4, 0xb9, 0xf6, 0x8f, 0x6a, 0xd4, 0x47,
	0x21, 0x13, 0x71, 0xe7, 0xe8, 0x63, 0x1a, 0xf5, 0x62, 0xa5, 0xa1, 0x8f, 0xeb, 0x23, 0x01, 0xca,
	0xb6, 0xcd, 0xf1, 0x7a, 0x6b, 0x13, 0x87, 0xe8, 0x13, 0x1a, 0x65, 0x38, 0xf6, 0xa0, 0xaf, 0xcb,
	0x4d, 0xf8, 0xfe, 0x29, 0x35, 0x05, 0x46, 0x12, 0x08, 0x2f, 0xc4, 0x02, 0xca, 0x5e, 0xfc, 0x4d,
	0xb2, 0x99, 0xf4, 0xc0, 0x94, 0x3a, 0x1f, 0x76, 0x80, 0x8e, 0xac, 0xf8, 0xfe, 0x94, 0xea, 0xc6,
	0x0c, 0x0b, 0x9c, 0x78, 0xdc, 0x82, 0xb7, 0x88, 0xc8, 0xcd, 0x07, 0xa7, 0x54, 0x67, 0xe5, 0x90,
	0x34, 0x1b, 0xd0, 0x43, 0x53, 0xea, 0x00, 0xcc, 0xa4, 0xe3, 0x79, 0x8f, 0x7e, 0x30, 0xa5, 0x7a,
	0x33, 0x03, 0xa4, 0x13, 0x40, 0x72, 0x59, 0x08, 0xba, 0x0c, 0xfd, 0xb0, 0x9c, 0x87, 0xd8, 0x23,
	0xc5, 0x7f, 0x81, 0x0a, 0xfa, 0xd1, 0x94, 0x5a, 0x4b, 0xe3, 0x9b, 0x46, 0xf2, 0xdc, 0xa4, 0x1f,
	0x4f, 0xa9, 0x63, 0x6d, 0xac, 0x4a, 0x5a, 0xe3, 0xf8, 0x0c, 0xe6, 0x2c, 0xfa, 0x49, 0x29, 0xc6,
	0xc1, 0x90, 0x9b, 0x7e, 0x66, 0xf7, 0x4f, 0x4b, 0x29, 0x49, 0xca, 0x4e, 0x1f, 0xc7, 0x70, 0x8a,
	0x7e, 0x56, 0x0a, 0x81, 0x46, 0xd1, 0xa5, 0x7c, 0xb0, 0x0c, 0x5d, 0x84, 0xa3, 0x87, 0xa7, 0xd4,
	0x35, 0x56, 0xd3, 0xd2, 0x1e, 0x86, 0xf0, 0xff, 0x4c, 0xd7, 0x25, 0x2d, 0xc0, 0x2d, 0xc2, 0x61,
	0xfd, 0x80, 0xf9, 0xb0, 0x19, 0x11, 0xde, 0x39, 0x83, 0x37, 0x18, 0x87, 0x87, 0x53, 0x7a, 0x8a,
	0x3e, 0x39, 0xad, 0x06, 0x58, 0x87, 0xce, 0xf9, 0x30, 0x37, 0x7c, 0xd8, 0x02, 0x46, 0xd8, 0x4f,
	0x4d, 0x6b, 0x1d, 0x4a, 0x1e, 0xae, 0x40, 0x3f, 0xc0, 0x7e, 0x24, 0xf3, 0xea, 0xcd, 0x15, 0xb5,
	0x4c, 0x65, 0x81, 0x73, 0xb2, 0x41, 0xc9, 0xa6, 0xd3, 0x27, 0x30, 0x80, 0x20, 0x39, 0x93, 0x08,
	0xdd, 0x52, 0x51, 0x5d, 0xaf, 0x80, 0x52, 0x79, 0xee, 0xfa, 0x5b, 0x2b, 0x6a, 0x32, 0x28, 0xb8,
	0x2c, 0x35, 0x6f, 0xab, 0xa8, 0xde, 0xd8, 0x0e, 0xc8, 0x35, 0xdd, 0x5e, 0x51, 0x69, 0x2b, 0xc0,
	0xc6, 0x56, 0x48, 0x61, 0x1d, 0xb8, 0xa3, 0xa2, 0xba, 0x60, 0x9b, 0x5c, 0x6b, 0xae, 0x77, 0x56,
	0xd4, 0xf1, 0xa1, 0x60, 0xc5, 0x7f, 0xe7, 0x58, 0xd2, 0xeb, 0xc7, 0x1a, 0xfe, 0x2e, 0xcd, 0x8a,
	0x3a, 0xd9, 0xe8, 0x9c, 0x4b, 0xb1, 0x99, 0x15, 0x77, 0xef, 0x53, 0xad, 0xd8, 0x0e, 0xc8, 0xad,
	0xb8, 0x67, 0x9f, 0x9a, 0x1f, 0x02, 0x98, 0x35, 0xaa, 0x3a, 0x67, 0xe9, 0xba, 0x7b, 0xef, 0x3e,
	0xad, 0xc7, 0xc6, 0x8c, 0x93, 0x79, 0x12, 0xc3, 0x32, 0xc8, 0xeb, 0x38, 0xc6, 0xe8, 0xd3, 0x55,
	0x75, 0x5b, 0x29, 0x8a, 0xf3, 0x8b, 0x3e, 0x53, 0xd5, 0x92, 0x47, 0xc0, 0x9a, 0x09, 0x77, 0xfb,
	0xa2, 0x5b, 0x42, 0xdd, 0xab, 0xb3, 0xfd, 0xb3, 0x55, 0xfb, 0x09, 0xd6, 0x63, 0x77, 0x84, 0x96,
	0x3d, 0x4b, 0x3e, 0x57, 0x55, 0xab, 0x45, 0xfb, 0x04, 0xb6, 0x13, 0xec, 0xc3, 0xfb, 0x03, 0x7d,
	0xbe, 0xaa, 0xe5, 0x64, 0x19, 0x26, 0x67, 0xfb, 0x85, 0xaa, 0x3a, 0x79, 0x34, 0x6c, 0x5a, 0x82,
	0xe8, 0x8b, 0x55, 0x75, 0x8a, 0x95, 0x20, 0x72, 0x5d, 0x5f, 0xda, 0x99, 0xdb, 0x8d, 0x09, 0xe1,
	0xc3, 0xf6, 0x56, 0x80, 0xbe, 0xbc, 0x33, 0xb7, 0x0c, 0x93, 0xeb, 0xfb, 0x4a, 0x55, 0xab, 0x97,
	0xa2, 0x7b, 0xd0, 0x57, 0xab, 0x6a, 0x29, 0xec, 0xe8, 0x3e, 0xf4, 0x35, 0x8d, 0xd7, 0x1c, 0x0e,
	0x02, 0xe2, 0x5d, 0x60, 0xdc, 0x13, 0x0b, 0x7a, 0x96, 0x47, 0x5f, 0xaf, 0xaa, 0xb5, 0x57, 0xc4,
	0x8c, 0x14, 0xdd, 0xad, 0xb9, 0xa2, 0xcd, 0x8a, 0xc0, 0xf1, 0x0e, 0x79, 0x8f, 0x46, 0x6d, 0x3b,
	0x32, 0xed, 0xb9, 0x1e, 0xba, 0x57, 0x33, 0x51, 0xe0, 0xea, 0x94, 0xc7, 0xc3, 0x56, 0x7d, 0x59,
	0xfe, 0xee, 0x81, 0xbe, 0xb1, 0x4d, 0x8f, 0x94, 0x2f, 0x25, 0x7e, 0x4c, 0x43, 0x9f, 0xe4, 0xb8,
	0xfb, 0x34, 0x13, 0x05, 0x2e, 0xbd, 0xa1, 0x75, 0xe3, 0xe2, 0x59, 0x32, 0x3c, 0x8f, 0xfd, 0x84,
	0xa0, 0x6f, 0x6a, 0xa1, 0x16, 0x98, 0x85, 0xa8, 0xcd, 0xe5, 0xf2, 0x34, 0x6a, 0x50, 0xdf, 0xda,
	0x66, 0x5f, 0x01, 0x91, 0x7b, 0xe2, 0xdb, 0xdb, 0x3d, 0x91, 0xd9, 0x2e, 0x76, 0x33, 0xe6, 0x13,
	0x87, 0x0d, 0x06, 0x38, 0xf0, 0xd0, 0x77, 0xaa, 0x6a, 0xdd, 0xa5, 0x6a, 0xce, 0xc3, 0x86, 0x0f,
	0xd5, 0x9d, 0x39, 0xe1, 0xbb, 0x55, 0x75, 0x1b, 0xd7, 0x7f, 0xc6, 0x42, 0xdf, 0xd3, 0xaa, 0x4e,
	0xdc, 0x74, 0x81, 0xac, 0xd5, 0x9a, 0x0b, 0xa3, 0x97, 0x0d, 0xb4, 0xec, 0x40, 0x0c, 0xf2, 0xfb,
	0xb5, 0x6b, 0x46, 0x51, 0xad, 0x05, 0x01, 0x60, 0x5c, 0xb9, 0x74, 0x45, 0xe8, 0x01, 0xad, 0x30,
	0xcb, 0x20, 0xe3, 0x51, 0x5c, 0xd5, 0x1f, 0x26, 0x12, 0xda, 0x84, 0xa5, 0x36, 0x1c, 0xbd, 0xfc,
	0xe6, 0x61, 0x21, 0x8c, 0xd1, 0x83, 0xda, 0xa5, 0xe9, 0x4a, 0x59, 0xb0, 0xed, 0xa1, 0xea, 0xec,
	0xcd, 0xbb, 0xad, 0xcb, 0x1a, 0xf3, 0xe2, 0x17, 0xba, 0x4c, 0x3f, 0xbc, 0x25, 0x6d, 0xf8, 0x4a,
	0x3b, 0x5b, 0x3e, 0x8b, 0x76, 0xc1, 0xfb, 0xf0, 0x60, 0xf1, 0xbc, 0x4e, 0x02, 0x0a, 0x7a, 0x26,
	0xa0, 0x0f, 0x1e, 0x29, 0xca, 0x52, 0x6f, 0x36, 0x38, 0x67, 0x1c, 0xed, 0x06, 0x1f, 0x1e, 0x2a,
	0x02, 0xda, 0x74, 0x40, 0x58, 0x12, 0xa3, 0x3d, 0x65, 0xc2, 0x85, 0x60, 0x03, 0x7a, 0x81, 0x87,
	0x26, 0xcb, 0x84, 0xe7, 0xd8, 0x12, 0x8e, 0xdd, 0x3e, 0xda, 0x0b, 0x39, 0x73, 0xb4, 0x28, 0x5c,
	0x0d, 0xc4, 0x0a, 0x15, 0xa4, 0x17, 0x3f, 0xaa, 0x8c, 0x19, 0x34, 0xf1, 0x45, 0xd6, 0x83, 0xc0,
	0x2c, 0x07, 0xc8, 0x50, 0xcd, 0x3a, 0x83, 0x29, 0xac, 0x5e, 0x6d, 0xe6, 0x70, 0x22, 0x9e, 0x48,
	0xe6, 0xec, 0xa5, 0x09, 0x6b, 0xba, 0x91, 0x2e, 0x76, 0x72, 0xa9, 0x4b, 0xc9, 0x28, 0x07, 0x9d,
	0x56, 0xe2, 0xba, 0x84, 0x78, 0xe0, 0x84, 0x5d, 0xe9, 0x55, 0xaa, 0x30, 0xd5, 0xd7, 0x69, 0x8a,
	0x47, 0xe7, 0x45, 0xf0, 0xd2, 0x09, 0xb1, 0xdf, 0x94, 0x00, 0xa0, 0x55, 0xc5, 0xb5, 0x6e, 0x17,
	0xca, 0x0f, 0x3c, 0xf5, 0x48, 0x20, 0x91, 0xb7, 0x54, 0x78, 0xec, 0x94, 0x18, 0x2b, 0x3b, 0x80,
	0x16, 0xc5, 0x2f, 0x88, 0xb2, 0xf0, 0x26, 0x21, 0xa7, 0x4e, 0xfe, 0x8f, 0x1b, 0xd3, 0x17, 0x01,
	0xda, 0x3b, 0xb7, 0xef, 0x89, 0x13, 0x4f, 0x32, 0xdd, 0xa8, 0xc7, 0xd6, 0x92, 0x6e, 0x74, 0xd3,
	0xc4, 0xae, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x19, 0x4d, 0xf1, 0xa1, 0x81, 0x16, 0x00, 0x00,
}
